In [1]:
import numpy as np
import pandas as pd

In [2]:
np.random.seed(42)

set1no = 900
set2no = 100

df1 = pd.DataFrame({
    "feature_1": np.random.normal(loc=0, scale=1, size=set1no),
    "feature_2": np.random.normal(loc=0, scale=1, size=set1no),
    "target": [0] * set1no
})

df2 = pd.DataFrame({
    "feature_1": np.random.normal(loc=0, scale=1, size=set2no),
    "feature_2": np.random.normal(loc=0, scale=1, size=set2no),
    "target": [1] * set2no
})

In [3]:
df1.head()

   feature_1  feature_2  target
0   0.496714   0.368673       0
1  -0.138264  -0.393339       0
2   0.647689   0.028745       0
3   1.523030   1.278452       0
4  -0.234153   0.191099       0

In [4]:
df2.head()

   feature_1  feature_2  target
0   1.901191   0.696954       1
1  -0.060661  -0.333819       1
2  -0.708407   1.173125       1
3  -1.513714   0.369642       1
4  -1.803140  -0.107302       1

In [5]:
df = pd.concat([df1, df2]).reset_index(drop=True)

In [6]:
df

     feature_1  feature_2  target
0     0.496714   0.368673       0
1    -0.138264  -0.393339       0
2     0.647689   0.028745       0
3     1.523030   1.278452       0
4    -0.234153   0.191099       0
..         ...        ...     ...
995  -0.370011   1.070150       1
996  -0.258796  -0.026521       1
997   1.598647  -0.881875       1
998   0.560919  -0.163067       1
999  -0.295480  -0.744903       1

[1000 rows x 3 columns]

In [7]:
df["target"].unique()

array([0, 1])

In [8]:
df["target"].value_counts()

target
0    900
1    100
Name: count, dtype: int64

In [9]:
# upsampling --> upsample minority
# downsampling --> downsample majority